@startuml
/' Start UML Class '/
package "main.java.game" #DDDDDD {
    abstract class EscapeGame {
        #int nbDigit
        #int nbTries
        #Boolean devMode
        #String name
        #String secretNum
        #int attemptsNum
        #ArrayList<Integer> minArr
        #ArrayList<Integer> maxArr
        #Boolean numFound
        #Boolean reachMaxAttempts
        #Boolean playAgain
        +PropertiesReader pr

        +EscapeGame(String name)
        {abstract} String generateSecretNum()
        {abstract} void adjustMinMax (String userInput)
        {abstract} void checkHumanAnswer (String userInput)
        {abstract} String generateAnswer(String userInput)
        {abstract} void run()
    }

    class ChallengerMode {
        +ChallengerMode()
    }

    class DefenderMode {
        +DefenderMode()
    }

    class DuelMode {
        +DuelMode()
    }

    class LaunchGame {
    }

    class GameCommonContent {
    }

   ChallengerMode --|> EscapeGame
   DefenderMode  --|> EscapeGame
   DuelMode  --|> EscapeGame
   ChallengerMode --|> DuelMode
   DefenderMode --|> DuelMode
}

package "main.java.utils" #DDDDDD {
    class PropertiesReader {
    }
    class RanChoice {
    }
    class ScannerTools {
    }
    class TextAnimation {
    }
}
@enduml