@startuml
/' Start Class Examples :
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
{static} size()
{abstract} void method()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}
/End Class Examples '/
/' Start UML Class '/
class ChallengerMode {
-String name
-String secretNum
-int attemptsNum
-ArrayList<Integer> minArr
-ArrayList<Integer> maxArr
-Boolean numFound
-Boolean reachMaxAttempts
-Boolean playAgain
~{static}PropertiesReader pr
-int nbDigit
-int nbTries
-int nbDigit

+void ChallengerMode()
+String generateSecretNum()
+void adjustMinMax (String userInput)
+void checkHumanAnswer (String userInput)
+void run()
}
@enduml